import React, { useContext, useEffect, useState } from "react";
import "./style.scss";
import axios from "axios";
import config from "@/config";
import { useParams } from "react-router-dom";
import { UserContext } from "../../context/UserContext";
const { backend_url } = config;
const AllQueries = () => {
  const id = useParams();
  const enquiry_id = id.enquiry_id;
  console.log(id);
  const [data, setData] = useState([]);
  const { user } = useContext(UserContext);

  const getQueriesData = async () => {
    try {
      const { data } = await axios.get(
        `${backend_url}/ep/singleEnqury/${enquiry_id}`,
        {
          headers: {
            Authorization: user.token,
          },
        }
      );
      console.log(data);
      setData(data);
    } catch (error) {
      console.log("enqury error");
      console.log(error);
    }
  };
  useEffect(() => {
    getQueriesData();
  }, []);

  return (
    <div className="main_container">
      <div className="main_query">
        {/* <p>Query Generated By</p> */}
        {data.map((data, i) => {
          return (
            <div>
              <ul>
                <li>Name : </li>
                <li>{data.enquirer.name}</li>
              </ul>
              <ul>
                <li>Name : </li>
                <li>{data.enquirer.phone_number}</li>
              </ul>
              <ul>
                <li>Name : </li>
                <li>{data.course.type}</li>
              </ul>
              <ul>
                <li>Name : </li>
                <li>{data.course.name}</li>
              </ul>
              <ul>
                <li>Name : </li>
                <li>{data.date}</li>
              </ul>
              <ul>
                <li>Name : </li>
                <li>{data.message}</li>
              </ul>
            </div>
          );
        })}
        {/* <ul>
          <li>Name : Ravi Kumar</li>
          <li>Phone Number : 939384283843</li>
          <li>Degree Related To : BTECH</li>
          <li>Course Related To : UG</li>
          <li>Date : 23/03/2024</li>
          <li>Mode : Offline</li>
          <li>Query : Regarding course enrollment</li>
          <li> Desc : Lorem ipsum dolor sit amet.</li>
        </ul> */}
        <div className="query_btn">
          <div className="btn1">
            <button>Pending</button>
          </div>
          <div className="btn2">
            <button>Replied</button>
          </div>
        </div>
      </div>
    </div>
  );
};

export default AllQueries;
