import React, { useContext, useEffect, useState } from "react";
import "./style.scss";
import axios from "axios";
import config from "@/config";
import { useParams } from "react-router-dom";
import { UserContext } from "../../context/UserContext";
const { backend_url } = config;
const AllQueries = () => {
  const id = useParams();
  const enquiry_id = id.enquiry_id;
  console.log(id);
  const [data, setData] = useState([]);
  const { user } = useContext(UserContext);
  const [rerender, setRerender] = useState(false);
  const getQueriesData = async () => {
    try {
      const { data } = await axios.get(
        `${backend_url}/ep/singleEnqury/${enquiry_id}`,
        {
          headers: {
            Authorization: user.token,
          },
        }
      );

      setData(data);
    } catch (error) {
      console.log("enqury error");
      console.log(error);
    }
  };
  const changeStatus = async () => {
    try {
      const { data } = await axios.put(
        `${backend_url}/ep/singleEnqury/${enquiry_id}`,
        {},
        {
          headers: {
            Authorization: user.token,
          },
        }
      );
      setRerender((prev) => !prev);
    } catch (error) {
      console.error(error);
    }
  };

  useEffect(() => {
    getQueriesData();
  }, []);
  useEffect(() => {
    getQueriesData();
  }, [rerender]);

  return (
    <div className="main_container">
      <div className="main_query">
        {/* <p>Query Generated By</p> */}
        {data.map((data, i) => {
          return (
            <div className="query-container">
              <div className="data">
                <div className="fields">Name : </div>
                <div>{data.enquirer.name}</div>
              </div>
              <div className="data">
                <div className="fields">Phone Number : </div>
                <div>{data.enquirer.phone_number}</div>
              </div>
              <div className="data">
                <div className="fields">Course Type : </div>
                <div>{data.course.type}</div>
              </div>
              <div className="data">
                <div className="fields">Course Name : </div>
                <div>{data.course.name}</div>
              </div>
              <div className="data">
                <div className="fields">Date : </div>
                <div>{data.date}</div>
              </div>
              <div className="data">
                <div className="fields">Status : </div>
                <div>{data.status}</div>
              </div>
              <div className="data">
                <div className="fields">Message : </div>
                <div>{data.message}</div>
              </div>
              <>
                <div className="query_btn  ">
                  {data.status == "Pending" ? (
                    <div className="btn1">
                      <button onClick={changeStatus}>
                        Change status to Solved
                      </button>
                    </div>
                  ) : data.status == "Solved" ? (
                    <div className="btn2">
                      <button onClick={changeStatus}>
                        Change status to Pending
                      </button>
                    </div>
                  ) : (
                    "hiiiii"
                  )}
                </div>
              </>
            </div>
          );
        })}
      </div>
    </div>
  );
};

export default AllQueries;
