import React from 'react'
import './style.scss'
const AllQueries = () => {
  return (
<div className="main_container">
 <p>Query Generated By</p>
 <ul>
  <li>Name : Ravi Kumar</li>
  <li>Phone Number : 939384283843</li>
  <li>Degree Related To : BTECH</li>
  <li>Course Related To : UG</li>
  <li>Date : 23/03/2024</li>
  <li>Mode : Offline</li>
 </ul>
<div className="sub_Container">
  <div className="main_query">
   <h3>
Regarding course enrollment</h3>
<p>Lorem ipsum dolor sit amet, consectetur adipisicing elit. Dolores aut maiores est saepe optio necessitatibus ipsam aspernatur quidem cum molestias, et voluptas rerum rem tempore! Cum, fugit. Magni, incidunt earum. Temporibus sequi fuga debitis eveniet molestiae illo, deleniti delectus accusantium ratione. Esse corrupti ab debitis dolorem quasi.</p>
<div className="query_btn">
   <div className="btn1">
<button>Pending</button>
   </div>
   <div className="btn2">
   <button>Replied</button>
   </div>
  </div>
  </div>
 </div>
</div>
  )
}

export default AllQueries
